databases:
  - name: gestionfinanciera-db
    plan: free
    region: oregon

services:
  - type: web
    name: back-gestionfinanciera
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: gestionfinanciera-db
          property: internalConnectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: gestionfinanciera-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: gestionfinanciera-db
          property: password
