databases:
  - name: gestionfinanciera-db
    plan: free
    region: oregon

services:
  - type: web
    name: back-gestionfinanciera
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_HOST
        fromDatabase:
          name: gestionfinanciera-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: gestionfinanciera-db
          property: port
      - key: DATABASE_NAME
        fromDatabase:
          name: gestionfinanciera-db
          property: database
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: gestionfinanciera-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: gestionfinanciera-db
          property: password
